Suraj787/mfi_customization

mfi_customization/hooks.py
mfi_customization/mfi/doctype/Asset.py
mfi_customization/mfi/doctype/task.py

* Asset Python wriiten, To update and delete and populate asset serial no doc.

* Python written for Task, shows respective task to users

---

mfi_customization/mfi/doctype/asset_serial_no/asset_serial_no.json
mfi_customization/mfi/doctype/issue.py
mfi_customization/public/js/issue.js

*Filtering logic applied on asset and serial no according to customer and location

*Fix:Filtering bug cleared in issue on field serial no.

---

mfi_customization/public/js/issue.js
mfi_customization/public/js/task.js

*in Task, Validation applied for attended time and completion time.

*Fix: in Issue, disable tassk via issue fixed

---

mfi_customization/mfi/doctype/issue.py
mfi_customization/mfi/patch/make_serial_no.py
mfi_customization/mfi/patch/set_doc_share_task.py
mfi_customization/public/js/issue.js
mfi_customization/public/js/task.js

* Patch added- 1) Serial No updation and 2) Docshare for task.

---

mfi_customization/mfi/patch/set_first_responded_on_issue.py
mfi_customization/public/js/issue.js

patch for set first responded on issue

[feature][issue status read only if task]

---

mfi_customization/mfi/report/issue_timelines/issue_timelines.py
mfi_customization/mfi/report/response_time_client/response_time_client.py

[fix: date format in response time client and issue timelines report],
[fix][resolution time = resolution date - attended time in issue timeline]
[fix][task as link field in response time client report]
[fix][get first responded on issue in issue timeline report]

[fix][date format in reports]

---

mfi_customization/hooks.py
mfi_customization/mfi/doctype/task.py

**Changes:**
- linking Issue's attachment files only when saving the Task for the first time.

feat: link attachments to task while creating one from issue

---

mfi_customization/mfi/doctype/issue.py

**Problem:**
Emails were not retrieved properly due to which it was showing the below error while closing an issue.
**Solved with the changes-**

fix: fix invalid email address issue on closing an issue

---

mfi_customization/mfi/doctype/material_request.py

**Changes:**
removed `task_` field from Material Request.

fix: remove field task_ on material request

---

mfi_customization/mfi/doctype/compatible_items/compatible_items.py

**Changes:**
Save asset after adding items in it

fix compatible items

---

mfi_customization/hooks.py
mfi_customization/mfi/doctype/issue.py
mfi_customization/mfi/doctype/task.py

**Changes/Additions:**
- Added email notification when Task is escalated.
- Added email notification for when issue is resolved over call.
- Mention customer name in email body when Issue is created.

Add email notifications

---

mfi_customization/public/js/issue.js

**Task:** https://bizmap.in/app/task/TASK-2022-00007
**Screenshot/gifs:**

fix(issue): fix setting of issue status to working

---

mfi_customization/mfi/doctype/machine_reading/machine_reading.py

**Task:** https://bizmap.in/app/task/TASK-2022-00006

fix: fix repetitive_call logic in machine_reading.py

---

mfi_customization/hooks.py
mfi_customization/mfi/doctype/comment.py
mfi_customization/mfi/doctype/material_request.py

**changes:**
- Remove `set_yeild_details` function
- Fix hooks (`on_submit` trigger for setting "Material Issued" status for Task and Issue was not getting triggered)

fix: fix hooks and material_request.py

---

mfi_customization/mfi/doctype/issue.py
mfi_customization/mfi/doctype/task.py

**Task:** https://bizmap.in/app/task/TASK-2022-00016

fix: fix email notification triggers for toner support email

---

mfi_customization/mfi/custom/issue.json

**Changes:**
Don't show `over call resolution` checkbox of Issue to customers.

fix: don't show over call resolution checkbox to customer

---

mfi_customization/hooks.py
mfi_customization/mfi/doctype/material_request.py

**Changes:**
- Remove notification for clients on creating and submitting a Material Request.

disable notifications for clients for material request

---

mfi_customization/mfi/doctype/issue.py
mfi_customization/public/js/issue.js

**Task:** https://bizmap.in/app/task/TASK-2023-00011

feat(support): fetch last reading as current readings while creating task from issue

---

mfi_customization/mfi/doctype/task.py

**Changes:**
- Commented code that sent emails to clients about Task.

don't send client email notifications about task

---

mfi_customization/public/js/task.js

**Task:** https://bizmap.in/app/task/TASK-2023-00017

fix(projects): make symptoms fields on task mandatory only whe status is working

---

mfi_customization/public/js/task.js

**Task:** https://bizmap.in/app/task/TASK-2023-00018

feat(projects): fetch today's date, asset's type on current reading of task

---

mfi_customization/public/js/issue.js

**Changes:**
- comment custom code for removing custom create task button on issue

comment custom code for removing custom create task button on issue
